<?php

/**
 * @file
 *   kgart_api.module
 *   API functions for Kovács Gábor project
 * Project:kogabor
 *
 * @developers:
 *    Gabor Szanto <hello@szantogabor.com>
 *    http://szantogabor.com
 *
 */

/*
 * This functions is used in art ct computed fields
 *
 *
 */
function kgart_api_art_image_url($size) {
  global $base_url;
  $default_image_dir = variable_get('kgart_image_path', 'images');
  if(!empty($default_image_dir)) {
    $dir = $default_image_dir . '/' . variable_get("kgart_image_path_$size", "/$size") ;
  } else {
    $dir = variable_get("kgart_image_path_$size", "/$size") ;
  }
  return $dir;
}

function computed_field_field_art_image_url_s_compute($node, $field, &$node_field) {
  if(!empty($node->field_art_image_path_s[0]['value'])) {
    $node_field[0]['value'] = kgart_api_art_image_url('s') . '/' . $node->field_art_image_path_s[0]['value'] . '/' . $node->nid . '_s.jpg';
  } else {
    $node_field[0]['value'] = kgart_api_art_image_url('s') . '/' . $node->nid . '_s.jpg';
 }
}

function computed_field_field_art_image_url_s_display($field, $element, $node) {
  return l($node->field_art_image_url_s[0]['value'], $node->field_art_image_url_s[0]['value'], array('absolute'=>TRUE, 'external'=>TRUE));
}

function computed_field_field_art_image_url_m_compute($node, $field, &$node_field) {
  if(!empty($node->field_art_image_path_m[0]['value'])) {
    $node_field[0]['value'] = kgart_api_art_image_url('m') . '/' . $node->field_art_image_path_m[0]['value'] . '/' . $node->nid . '_m.jpg';
  } else {
    $node_field[0]['value'] = kgart_api_art_image_url('m') . '/' . $node->nid . '_m.jpg';
  }
}

function computed_field_field_art_image_url_m_display($field, $element, $node) {
  return l($node->field_art_image_url_m[0]['value'], $node->field_art_image_url_m[0]['value'], array('absolute'=>TRUE, 'external'=>TRUE));
}

function computed_field_field_art_image_url_l_compute($node, $field, &$node_field) {
  if(!empty($node->field_art_image_path_l[0]['value'])) {
    $node_field[0]['value'] = kgart_api_art_image_url('l') . '/' . $node->field_art_image_path_l[0]['value'] . '/' . $node->nid . '_l.tif';
  } else {
    $node_field[0]['value'] = kgart_api_art_image_url('l') . '/' . $node->nid . '_l.tif';
  }
}

function computed_field_field_art_image_url_l_display($field, $element, $node) {
  return l($node->field_art_image_url_l[0]['value'], $node->field_art_image_url_l[0]['value'], array('absolute'=>TRUE, 'external'=>TRUE));
}

/*
 * Helper function to increment printed serieal value for overriden theme_serial_formatter_default($element)
 */
function kgart_api_inc_serial($value, $number = 6) {
  while (strlen($value) < $number) {
    $value = '0' . $value;
  }
  return $value;
}