<?php

/**
 * @file
 *   Custom administration pages and functions for Kovács Gábor gyűjtemény site.
 *   Project:Young Element
 *
 * @developers:
 *    Gabor Szanto <hello@szantogabor.com>
 *    http://szantogabor.com
 *
 */

/**
 * Implementation of hook_menu().
 *
 * @return An array of menu items.
 */
function kgart_admin_menu() {
  $items = array();

  $items['content-admin/site_defaults'] = array(
    'title' => 'Site default settings',
    'description' => 'description',
    'page callback' => 'kgart_admin_page',
    //'page arguments' => array('callback_arg'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/kgart_admin.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_form_alter().
 */
function kgart_admin_form_alter(&$form, $form_state, $form_id) {
  if ($form['#id'] == 'node-form') {
    $type = $form['type']['#value'] ;
    $type_name = check_plain(node_get_types('name', $type));
    $node = $form['#node'];

    //Add nid to node forms
    $form['show_nid'] = array (
      '#prefix' => '<div id="show-nid" class="form-item">',
      '#suffix' => '</div>',
      '#value' => '<label>' . t('@type ID', array('@type' => t($type_name))) . ': </label>' . $node->nid,
      '#type' => 'markup',
    );
    //dsm(get_defined_vars());
  }
}