<?php

/**
 * @file
 *   Custom administration pages and functions for Kovács Gábor gyűjtemény site.
 *   Project:Young Element
 *
 * @developers:
 *    Gabor Szanto <hello@szantogabor.com>
 *    http://szantogabor.com
 *
 */

/**
 * Implementation of hook_menu().
 *
 * @return An array of menu items.
 */
function kgart_admin_menu() {
  $items = array();

  $items['content-admin/site_defaults'] = array(
    'title' => 'Site default settings',
    'description' => 'description',
    'page callback' => 'kgart_admin_page',
    //'page arguments' => array('callback_arg'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/kgart_admin.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_form_alter().
 */
function kgart_admin_form_alter(&$form, $form_state, $form_id) {
  if ($form['#id'] == 'node-form') {
    $type = $form['type']['#value'] ;
    $type_name = check_plain(node_get_types('name', $type));
    $node = $form['#node'];

    if ($type == 'art_object') {
      //we need manually short some elements.
      $form['#after_build'][] = 'kgart_admin_move_node_options';
      $form['#validate'][] = 'kgart_admin_art_object_node_form_validate';
    }

    //Add nid to node forms
    $form['show_nid'] = array (
      '#prefix' => '<div id="show-nid" class="form-item">',
      '#suffix' => '</div>',
      '#value' => '<label>' . t('@type ID', array('@type' => t($type_name))) . ': </label>' . $node->nid,
      '#type' => 'markup',
    );
    //dsm(get_defined_vars());
  }
}

/*
 * After build function for art_object_node_form
 */
function kgart_admin_move_node_options($form, &$form_state) {
  //Just inherit the original node options elementes, need to insert to flag fieldset
  //On custom form validation, we get back this values to the original node options
  $form['flag']['status'] = $form['options']['status'];
  $form['flag']['promote'] = $form['options']['promote'];

  //Short flags
  if (isset($form['flag']['protected'])) {
    $form['flag']['protected']['#weight'] = 1;
  }
  if (isset($form['flag']['sold'])) {
    $form['flag']['sold']['#weight'] = 2;
  }
  if (isset($form['flag']['new_picture'])) {
    $form['flag']['new_picture']['#weight'] = 3;
  }
  if (isset($form['flag']['promote'])) {
    $form['flag']['promote']['#weight'] = 4;
  }
  if (isset($form['flag']['status'])) {
    $form['flag']['status']['#weight'] = 5;
  }
  dsm(get_defined_vars());
  return $form;
}

function kgart_admin_art_object_node_form_validate(&$form_state, $form) {
  $form_state['#redirect'] = NULL;
}