<?php

function inplace_extra_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['type']) && isset($form['#node']) && $form['type']['#value'] . '_node_form' == $form_id) {

    foreach($form as $key => $field) {
      if(substr($key, 0, 6) === "group_") {
        foreach($form[$key] as $keyg => $fieldg) {
          if(substr($keyg, 0, 6) === "field_") {
            if(isset($form[$keyg."_hu"])) {
              $form[$key][$keyg."_hu"] = $form[$keyg."_hu"];
              unset($form[$keyg."_hu"]);
            }
            if(isset($form[$keyg."_en"])) {
              $form[$key][$keyg."_en"] = $form[$keyg."_en"];
              unset($form[$keyg."_en"]);
            }
          }
        }
      }
    }
    
    foreach($form as $key => $field) {
      if(substr($key, 0, 6) === "group_") {
        foreach($field as $keyf => $fieldf) {
          if(substr($keyf, 0, 6) === "field_") {
            global $language;
            if(isset($form[$key][$keyf."_hu"])) {
              $form[$key][$keyf][0]['#title'] .= " (". $language->language .")";
              $form[$key][$keyf."_hu"][0]['#title'] .= " (hu)";
            }
            if(isset($form[$key][$keyf."_en"])) {
              $form[$key][$keyf][0]['#title'] .= " (". $language->language .")";
              $form[$key][$keyf."_en"][0]['#title'] .= " (en)";
            }
          }
        }
      }
      if(substr($key, 0, 6) === "field_") {
        global $language;
        if(isset($form[$key."_hu"])) {
          $form[$key][0]['#title'] .= " (". $language->language .")";
          $form[$key."_hu"][0]['#title'] .= " (hu)";
        }
        if(isset($form[$key."_en"])) {
          $form[$key][0]['#title'] .= " (". $language->language .")";
          $form[$key."_en"][0]['#title'] .= " (en)";
        }
      }
    }
    $lang = $language->language == "en" ? "hu" : "en";
    if (auto_nodetitle_get_setting($form['#node']->type) == AUTO_NODETITLE_ENABLED) {
      // we will autogenerate the title later, just hide the title field in the meanwhile
      $form['title_'.$lang]['#value'] = 'ant';
      $form['title_'.$lang]['#type'] = 'value';
      $form['title_'.$lang]['#required'] = FALSE;
      $form['#submit'][] = 'inplace_extra_node_form_submit';
    }
    //dpm($form);
  }  
}

/**
 * Makes sure the node preview is shown right.
 * It gets the node object, modifies the title, and updates the node in the form_state.
 */
function inplace_extra_node_form_submit($form, &$form_state) {
  // Only do something, if the user clicked the preview button.
  if (isset($form_state['clicked_button']['#submit']) && in_array('node_form_build_preview', $form_state['clicked_button']['#submit'])) {
    $setting = auto_nodetitle_get_setting($form_state['values']['type']);
    if ($setting == AUTO_NODETITLE_ENABLED) {
      $node = node_submit($form_state['values']);
      inplace_extra_set_title($node);
      $form_state['values'] = (array)$node;
    }
  }
}

/**
 * Sets the automatically generated nodetitle for the node
 */
function inplace_extra_set_title(&$node) {
  global $language;
  $types = node_get_types();
  $pattern = variable_get('ant_pattern_'. $node->type, '');
  $lang = $language->language == "en" ? "title_hu" : "title_en";
  if (trim($pattern)) {
    $node->changed = time();
    $node->$lang = _auto_nodetitle_patternprocessor($pattern, $node);
  }
  else if ($node->nid) {
    $node->$lang = t('@type @node-id', array('@type' => $types[$node->type]->name, '@node-id' => $node->nid));
  }
  else {
    $node->$lang = t('@type', array('@type' => $types[$node->type]->name));
  }
}
